name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest  # Using macOS runner to run iOS simulator

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use Node.js 16 (adjust if necessary)

      # Step 3: Install npm dependencies
      - name: Install dependencies (npm)
        run: |
          cd Concordia_Campus_App
          npm install

      # Step 4: Install CocoaPods dependencies for iOS
      - name: Install CocoaPods dependencies
        run: |
          cd Concordia_Campus_App/ios
          gem install cocoapods  # Install CocoaPods gem
          pod install  # Install iOS dependencies via CocoaPods

      # Step 5: Install Maestro CLI for E2E testing
      - name: Install Maestro CLI
        run: |
          curl -sSL https://github.com/maestro-dev/maestro/releases/download/v0.12.0/maestro-cli-darwin.zip -o maestro-cli.zip
          unzip maestro-cli.zip
          mv maestro /usr/local/bin  # Move Maestro to the path for easy access

      # Step 6: Run iOS E2E tests with Maestro
      - name: Run iOS E2E tests with Maestro
        run: |
          # List available simulators (optional, useful for debugging or choosing a specific device)
          xcrun simctl list devices

          # Run the Maestro tests on a specified simulator device (e.g., iPhone 13)
          maestro test Concordia_Campus_App/maestro/App.yml --device "iPhone 13" --platform "ios"

