name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd Concordia_Campus_App
          npm install

      - name: Run tests
        run: |
          cd Concordia_Campus_App
          npm run test --coverage

      - name: Verify test results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed!"
            exit 1
          fi

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: JonathanDannessa/SE390-Mini-capstone-project

      - name: Start iOS simulator
        run: |
          cd Concordia_Campus_App
          npx expo start --ios --non-interactive
