name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd Concordia_Campus_App
          npm install

      - name: Run postinstall script
        run: |
          cd Concordia_Campus_App
          npm run postinstall


      - name: Run Jest unit tests
        run: |
          cd Concordia_Campus_App
          npm run test --coverage

      - name: Verify test results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed!"
            exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Add Fastlane to handle any build or Maestro test execution steps

      - name: Install Fastlane
        run: |
          sudo gem install fastlane -NV

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Run Maestro E2E Tests (if needed)
        run: |
          cd Concordia_Campus_App
          fastlane ios maestro_tests  # Assuming you have a lane for running your Maestro tests



