name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (npm)
        run: |
          cd Concordia_Campus_App
          npm install

      - name: Install CocoaPods dependencies
        run: |
          cd Concordia_Campus_App/ios
          gem install cocoapods
          pod install

      - name: Install Fastlane (via RubyGems)
        run: |
          gem install fastlane

      - name: Select Xcode version
        run: |
          xcode-select -s /Applications/Xcode_15.4.app

      - name: Build and run on iOS simulator using Fastlane
        run: |
          cd Concordia_Campus_App/ios
          fastlane ios simulator

      - name: Run tests
        run: |
          cd Concordia_Campus_App
          npm run test --coverage

      - name: Verify test results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed!"
            exit 1
          fi

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: MTEspo/SE390-Mini-capstone-project

