name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest  # Using macOS runner to run iOS simulator

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use Node.js 16 (adjust if necessary)

      # Step 3: Install npm dependencies
      - name: Install dependencies (npm)
        run: |
          cd Concordia_Campus_App
          npm install

      # Step 4: Install CocoaPods dependencies for iOS
      - name: Install CocoaPods dependencies
        run: |
          cd Concordia_Campus_App/ios
          gem install cocoapods  # Install CocoaPods gem
          pod install  # Install iOS dependencies via CocoaPods

      # Step 5: Install Maestro CLI for E2E testing
      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH  # Add Maestro to PATH

      # Step 6: Run iOS E2E tests with Maestro
            # Step 6: Run iOS E2E tests with Maestro
      - name: Run iOS E2E tests with Maestro
        run: |
          # Install and run the app on the simulator
          cd Concordia_Campus_App
          npx expo run:ios --bundle-identifier "com.concordia.campusapp"

          # Navigate to the Maestro folder
          cd maestro

          # Run the Maestro tests on the started simulator
          maestro test App.yml

