name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install dependencies (npm)
        run: |
          cd Concordia_Campus_App
          npm install

      - name: Run unit tests
        run: |
          cd Concordia_Campus_App
          npm run test --coverage

      - name: Verify test results
        run: |
          if [ $? -ne 0 ]; then
            echo "Tests failed!"
            exit 1
          fi

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH  # Add Maestro to PATH

      - name: Run iOS E2E tests with Maestro
        run: |
          export MAESTRO_DRIVER_STARTUP_TIMEOUT=600
          # Start the app on the simulator in the background
          cd Concordia_Campus_App
          nohup npx expo run:ios &  

          # Wait for 12 minutes to allow the app to launch
          echo "Waiting for the app to launch..."
          sleep 1000

          echo "Proceeding with Maestro tests."

          # Navigate to the Maestro folder and run the tests
          cd maestro
          maestro test App.yml


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: JonathanDannessa/SE390-Mini-capstone-project


