name: SonarCloud Analysis

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  sonarcloud:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

        with:
          args: >
            -Dsonar.organization="SOEN_390_mini_capstone_project"    
            -Dsonar.projectKey="george-ezzat_SE390-Mini-capstone-project"
            -Dsonar.branch.name="main"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
