name: SonarCloud Analysis

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  sonarcloud:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization="SOEN 390 mini capstone project"    
            -Dsonar.projectKey="george-ezzat_SE390-Mini-capstone-project"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
